const ClaimsCardStyles = {
  heading: {
    color: "#383D4E",
    fontSize: "20px",
    fontStyle: "normal",
    fontWeight: 400,
    fontFamily: "Playfair Display",
    lineHeight: "110%",
  },
  claimsCard: {
    marginTop: "22px",
    height: "112px",
    display: "grid",
    gridTemplateColumns: "0.5fr repeat(6,1fr)",
    alignItems: "center",
    padding: "0px 30px",
    border: "1px solid #C9E1EC",
    boxShadow: "0px 0px 10px 0px rgba(0, 0, 0, 0.1)",
  },
  claimsCardItem: {
    display: "grid",
    gap: "12px",
  },
  claimsCardItemHeading: {
    overflow: "hidden",
    color: "#1D252B",
    textOverflow: "ellipsis",
    fontSize: "18px",
    fontFamily: "Noto Sans",
    fontStyle: "normal",
    fontWeight: "400",
    lineHeight: "110%",
  },
  claimsCartItemContent: {
    textOverflow: "ellipsis",
    color: "#1D252B",
    fontSize: "18px",
    fontStyle: "normal",
    fontFamily: "Noto Sans",
    fontWeight: "300",
    lineHeight: "110%",
  },
  claimsCardButton: {
    width: 155,
    height: 40,
    padding: "16px 12px",
    borderRadius: 40,
    backgroundColor: "#3F3F3F",
    boxShadow: "0px 6px 10px 0px rgba(63, 63, 63, 0.3)",
    color: "var(--Default-White, #FFF)",
    fontWeight: 400,
    fontFamily: "Noto Sans",
  },
};
export default ClaimsCardStyles;
