export const BasicInfoQuickStyles = {
    BasicInfoQuickActionContainer: {
        boxShadow: '0px 2px 4px 0px rgba(0, 0, 0, 0.09) inset',
        color: '#1D252B',
        background: "#F3F5F6",
        borderRadius: '0 10px 10px 0',
        "@media (max-width: 599px)": {
            borderRadius: '0 0 10px 10px',
        },
        "@media (min-width: 605px) and (max-width: 1364px)": {
            padding: "13px 15px 9.5px 15px",
        },
        "@media (min-width: 1365px) and (max-width: 1920px)": {
            padding: "26px 30px 19px 30px",
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'space-around',
        },
    },
    BasicInfoQuickActionCard: {
        "@media (max-width: 599px)": {
            display: "flex",
        },
        "@media (min-width: 600px) and (max-width: 1024px)": {
            paddingLeft: "25px",
            paddingRight: "25px",
            marginTop: "30px",
        },
        "@media (min-width: 1024px) and (max-width: 1920px)": {
            display: "grid",
            gridTemplateColumns: "repeat(2, 1fr)",
            gridAutoRows: "minmax(10px, auto)",
            gap: "10px",
            columnGap: '20px',
        },
    },
    buttonStyle: {
        textTransform: "none",
        display: "flex",
        height: "35px",
        width: "fit-content",
        justifyContent: "center",
        alignItems: "center",
        borderRadius: "20px",
        backgroundColor: "#FFF",
        padding: "8.5px 15px",
        minWidth: "151px",
        flexShrink: 0,
        color: "#1D252B",
        fontSize: "16px",
        fontFamily: "Noto Sans",
        lineHeight: "110%",
        fontWeight: 300,
        fontStyle: "normal",
    },
    mobileContainer: {
        display: "flex",
        alignItems: "center",
        marginTop: "15px",
        marginBottom: "15px",
        marginLeft: "20px",
        marginRight: "20px",
        justifyContent: "space-between",
    },
}