const ActivityStyles = {
  container: {
    width: "auto",
    height: "642px",
    padding: "0px 28px",
    // marginTop:"30px",
    // position:"relative",
    "@media (min-width: 360px) and (max-width: 600px)": {
      padding: "0px 20px",
    },
  },

  oneCard: {
    height: "auto",
    width: "100%",
    display: "flex",
    gap: "34.06px",
    border: "0px",
    boxShadow: "0",
    borderBottom: "1px solid rgba(201, 225, 236, 1)",
    "@media (min-width: 360px) and (max-width: 600px)": {
      width: "96.02%",
      height: "auto",
      border: "1px solid rgba(201, 225, 236, 1)",
      borderColor: "rgba(201, 225, 236, 1)",
      background: "rgba(255, 255, 255, 1)",
      marginTop: "20px",
      borderRadius: "20px",
      gap: "17.46px",
    },
    "@media (min-width: 600px)": {
      "&:hover": {
        boxShadow: "0px 2px 4px 0px rgba(0, 0, 0, 0.09) inset",
        background: "rgba(243, 245, 246, 1)",
        padding: "0px 28px 0px 28px",
        marginLeft: "-28px",
      },
    },
  },
  logo: {
    width: "37.94px",
    marginTop: "20px",
    marginLeft: "30px",
    "@media (min-width: 360px) and (max-width: 600px)": {
      width: "46.36px",
      height: "48.88px",
      marginLeft: "20px",
    },
  },
  cardContent: {
    marginTop: "23px",
    height: "auto",
    width: "auto",
    "@media (min-width: 360px) and (max-width: 600px)": {
      marginTop: "20px",
      height: "auto",
      width: "auto",
    },
  },
  heading: {
    width: "auto",
    height: "22px",
    fontSize: "20px",
    fontWeight: "400",
    lineHeight: "22px",
    letterSpacing: "0em",
    textAlign: "left",
    "@media (min-width: 360px) and (max-width: 600px)": {
      height: "18px",
      fontSize: "16px",
      fontWeight: "400",
      lineHeight: "18px",
      letterSpacing: "0em",
      textAlign: "left",
    },
  },
  description: {
    width: "auto",
    height: "20px",
    marginTop: "6px",
    left: "132px",
    fontSize: "16px",
    fontWeight: "300",
    lineHeight: "20px",
    letterSpacing: "0em",
    textAlign: "left",
    "@media (min-width: 360px) and (max-width: 600px)": {
      height: "18px",
      fontSize: "16px",
      fontWeight: "300",
      lineHeight: "18px",
      letterSpacing: "0em",
      textAlign: "left",
    },
  },

  date: {
    width: "auto",
    height: "20px",
    marginTop: "7px",
    marginBottom: "21px",
    fontSize: "16px",
    fontWeight: "300",
    lineHeight: "20px",
    letterSpacing: "0em",
    textAlign: "left",
    "@media (min-width: 360px) and (max-width: 600px)": {
      height: "18px",
      marginBottom: "20px",
      fontSize: "16px",
      fontWeight: "300",
      lineHeight: "18px",
      letterSpacing: "0em",
      textAlign: "left",
    },
  },
  claimNumberClosureReason: {
    display: "flex",
    "@media (min-width: 360px) and (max-width: 600px)": {
      flexDirection: "column",
    },
  },
  line: {
    margin: "10px 10px 0px 10px",
    "@media (min-width: 360px) and (max-width: 600px)": {
      display: "none",
    },
  },

  closureReason: {
    width: "auto",
    height: "20px",
    marginTop: "12.5px",
    fontSize: "16px",
    fontWeight: "300",
    lineHeight: "20px",
    letterSpacing: "0em",
    textAlign: "left",
    "@media (min-width: 360px) and (max-width: 600px)": {
      height: "18px",
      fontSize: "16px",
      fontWeight: "300",
      lineHeight: "18px",
      letterSpacing: "0em",
      textAlign: "left",
      marginTop: "5px",
      marginBottom: "15px",
    },
  },
  claimNumber: {
    width: "auto",
    height: "20px",
    marginTop: "12.5px",
    fontSize: "16px",
    fontWeight: "300",
    lineHeight: "20px",
    letterSpacing: "0em",
    textAlign: "left",
  },
  payoutAmount: {
    width: "auto",
    height: "20px",
    marginTop: "12.5px",
    fontSize: "16px",
    fontWeight: "300",
    lineHeight: "20px",
    letterSpacing: "0em",
    textAlign: "left",
  },
  hoveredImage1: {
    width: "40px",
  },
  images: {
    display: "flex",
    flexDirection: "row",
    alignItems: "Center",
    position: "absolute",
    // left: "64.0549%",
    left: "90.0549%",
    marginTop: "50px",
    cursor: "pointer",
    "@media (min-width: 360px) and (max-width: 600px)": {
      display: "none",
    },
  },
  ellipsis: {
    display: "none",
    "@media (min-width: 360px) and (max-width: 600px)": {
      position: "absolute",
      display: "block",
      marginTop: "20px",
      marginLeft: "72%",
    },
  },
};
export default ActivityStyles;
