const AcknowledgementStyles = {
  container: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
    width: "300px",
    linearGradient: "(180deg, #FBFDFC 0%, #E5F6FE 100%)",
  },
  successImage: {
    width: "60px",
    height: "60px",
    margin: "0px auto",
    img: {
      width: "100%",
      height: "100%",
    },
  },
  claimData: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  agentData: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  claimSubmittedText: {
    fontFamily: "Playfair Display",
    fontSize: "20px",
    fontWeight: "600",
    lineHeight: "20px",
    textAlign: "center",
  },
  referenceNumberText: {
    fontFamily: "Noto Sans",
    fontSize: "14px",
    fontWeight: "400",
    lineHeight: "19.1px",
    textAlign: "center",
    color: "#222222",
  },
  referenceNumber: {
    fontFamily: "Noto Sans",
    fontSize: "20px",
    fontWeight: "700",
    lineHeight: "20.8px",
    textAlign: "center",
    color: "#222222",
  },
  contactAgentText: {
    fontFamily: "Noto Sans",
    fontSize: "14px",
    fontWeight: "400",
    lineHeight: "19.1px",
    textAlign: "center",
    color: "#222222",
  },
  agentName: {
    fontFamily: "Noto Sans",
    fontSize: "18px",
    fontWeight: "700",
    lineHeight: "18px",
    textAlign: "center",
    color: " #000000",
  },
  agentNumber: {
    fontFamily: "Noto Sans",
    fontSize: "16px",
    fontWeight: "400",
    lineHeight: "21.82px",
    textAlign: "center",
    color: " #171717",
  },
  agentMailId: {
    fontFamily: "Noto Sans",
    fontSize: "16px",
    fontWeight: "400",
    lineHeight: "24px",
    textAlign: "center",
    color: "#171717",
  },
  button: {
    width: "300px",
    height: "30px",
    padding: "16px 12px 16px 12px",
    gap: "0px",
    borderRadius: "40px",
    background: "#3F3F3F",
    boxShadow: "0px 6px 10px 0px #3F3F3F4D",
    fontFamily: "Noto Sans",
    fontSize: "14px",
    fontWeight: "400",
    lineHeight: "18px",
    textAlign: "center",
    textTransform: "none",
  },
  agentContact: {
    display: "flex",
    alignItems: "center",
    gap: "2px",
    justifyContent: "center",
    img: {
      width: "20px",
      height: "20px",
    },
  },
  agentemailContact: {
    display: "flex",
    alignItems: "center",
    gap: "2px",
    justifyContent: "center",
    img: {
      width: "20px",
      height: "20px",
    },
  },
};
export default AcknowledgementStyles;
