export const CityName = [
  { state: "OK", value: "Oklahoma", label: "Oklahoma" },
  { state: "Andra Predesh", value: "Hyderabad", label: "Hyderabad" },
  { state: "Andra Predesh", value: "Visakhapatnam", label: "Visakhapatnam" },
  { state: "Andra Predesh", value: "Vijayawada", label: "Vijayawada" },
  { state: "Andra Predesh", value: "Guntur", label: "Guntur" },
  { state: "Telangana", value: "Hyderabad", label: "Hyderabad" },
  { state: "Telangana", value: "Warangal", label: "Warangal" },
  { state: "Telangana", value: "Nizamabad", label: "Nizamabad" },
  { state: "Telangana", value: "Karimnagar", label: "Karimnagar" },
  { state: "Karnataka", value: "Bangalore", label: "Bangalore" },
  { state: "Karnataka", value: "Mysore", label: "Mysore" },
  { state: "Karnataka", value: "Hubli", label: "Hubli" },
  { state: "Karnataka", value: "Mangalore", label: "Mangalore" },
  { state: "Mumbai", value: "Mumbai", label: "Mumbai" },
  { state: "Mumbai", value: "Thane", label: "Thane" },
  { state: "Mumbai", value: "Navi Mumbai", label: "Navi Mumbai" },
  { state: "Mumbai", value: "Pune", label: "Pune" },
  { state: "NY", value: "NYC", label: "New York City" },
  { state: "NY", value: "Buffalo", label: "Buffalo" },
  { state: "NY", value: "Rochester", label: "Rochester" },
  { state: "NY", value: "Syracuse", label: "Syracuse" },
  { state: "CA", value: "Los Angeles", label: "Los Angeles" },
  { state: "CA", value: "San Francisco", label: "San Francisco" },
  { state: "CA", value: "San Diego", label: "San Diego" },
  { state: "CA", value: "Sacramento", label: "Sacramento" },
  { state: "TX", value: "Houston", label: "Houston" },
  { state: "TX", value: "Dallas", label: "Dallas" },
  { state: "TX", value: "Austin", label: "Austin" },
  { state: "TX", value: "San Antonio", label: "San Antonio" },
  { state: "FL", value: "Miami", label: "Miami" },
  { state: "FL", value: "Orlando", label: "Orlando" },
  { state: "FL", value: "Tampa", label: "Tampa" },
  { state: "FL", value: "Jacksonville", label: "Jacksonville" },
  { state: "ON", value: "Toronto", label: "Toronto" },
  { state: "ON", value: "Ottawa", label: "Ottawa" },
  { state: "ON", value: "Mississauga", label: "Mississauga" },
  { state: "ON", value: "Hamilton", label: "Hamilton" },
  { state: "QC", value: "Montreal", label: "Montreal" },
  { state: "QC", value: "Quebec City", label: "Quebec City" },
  { state: "QC", value: "Laval", label: "Laval" },
  { state: "QC", value: "Gatineau", label: "Gatineau" },
  { state: "BC", value: "Vancouver", label: "Vancouver" },
  { state: "BC", value: "Victoria", label: "Victoria" },
  { state: "BC", value: "Surrey", label: "Surrey" },
  { state: "BC", value: "Burnaby", label: "Burnaby" },
  { state: "AB", value: "Calgary", label: "Calgary" },
  { state: "AB", value: "Edmonton", label: "Edmonton" },
  { state: "AB", value: "Red Deer", label: "Red Deer" },
  { state: "AB", value: "Lethbridge", label: "Lethbridge" },
  { state: "BKO", value: "ACI2000", label: "ACI 2000" },
  { state: "BKO", value: "Badalabougou", label: "Badalabougou" },
  { state: "BKO", value: "Medina-Coura", label: "Medina Coura" },
  { state: "BKO", value: "Niamakoro", label: "Niamakoro" },
  { state: "GAO", value: "Gao", label: "Gao" },
  { state: "GAO", value: "Bamba", label: "Bamba" },
  { state: "GAO", value: "Ansongo", label: "Ansongo" },
  { state: "GAO", value: "Menaka", label: "Menaka" },
  { state: "KAY", value: "Kayes", label: "Kayes" },
  { state: "KAY", value: "Bafoulabe", label: "Bafoulabe" },
  { state: "KAY", value: "Nioro", label: "Nioro" },
  { state: "KAY", value: "Yelimane", label: "Yelimane" },
  { state: "SEG", value: "Segou", label: "Segou" },
  { state: "SEG", value: "San", label: "San" },
  { state: "SEG", value: "Markala", label: "Markala" },
  { state: "SEG", value: "Niono", label: "Niono" },
  { state: "NSW", value: "Sydney", label: "Sydney" },
  { state: "NSW", value: "Newcastle", label: "Newcastle" },
  { state: "NSW", value: "Wollongong", label: "Wollongong" },
  { state: "NSW", value: "Central Coast", label: "Central Coast" },
  { state: "VIC", value: "Melbourne", label: "Melbourne" },
  { state: "VIC", value: "Geelong", label: "Geelong" },
  { state: "VIC", value: "Ballarat", label: "Ballarat" },
  { state: "VIC", value: "Bendigo", label: "Bendigo" },
  { state: "QLD", value: "Brisbane", label: "Brisbane" },
  { state: "QLD", value: "Gold Coast", label: "Gold Coast" },
  { state: "QLD", value: "Sunshine Coast", label: "Sunshine Coast" },
  { state: "QLD", value: "Cairns", label: "Cairns" },
  { state: "WA", value: "Perth", label: "Perth" },
  { state: "WA", value: "Fremantle", label: "Fremantle" },
  { state: "WA", value: "Broome", label: "Broome" },
  { state: "WA", value: "Albany", label: "Albany" },
];
