import myClaimsIcon from "../assets/myClaimsIcon.svg";
import carIcon from "../assets/car.svg";
import roadsideAssistanceIcon from "../assets/roadsideAssistanceIcon.svg";
import paymentHistoryIcon from "../assets/Group 1000009236.svg";
import starIcon from "../assets/star.svg";
import learnAboutIcon from "../assets/Group 1000009237.svg";
import viewAllArrow from "../assets/viewAllArrow.svg";
import leftArrow from "../assets/left_arrow.svg";
export const customerPath = [];
export const SETTINGS_AND_PREFERENCES = "Setting and Preferences";
export const LANGUAGE = "Language";
export const SELECT_LANGUAGE = "Select Language you are comforable with";
export const NOTIFICATIONS = "Notifications";
export const LET_US_KNOW =
  "Let us know how and when you would like to be notified";
export const PROFILE_DETAILS_HEADING = "Profile Details";

export const policiesHeading = "Here Is Your List Of Policies";
export const quickReferences = "Quick References For You";
export const footerLeftText = "© 2024 Smart IMS. All rights reserved.";
export const termsAndService = "Terms of Service";
export const privatePolicy = "Privacy Policy";
export const viewAll = "View All";
export const trackYourClaim = "Track Your Claim";
export const renewalAmount = "Renewal Amount :";
export const renewNow = "Renew Now";
export const duesDate = "Due Date :";
export const terms = " : Tax and Fee may apply.";
export const newClaim = "New Claim";
export const paymentHistory = "Payment History";
export const roadSideAssistance = "Roadside Assistance";
export const learnAbout = "Learn about Insurance";
export const name = "Mathew";
export const viewPast = "View Past Claims";
export const attentionText = "Things Need Your Attention";
export const breadcrumbText = "12AW1145G057 |  Auto_Garage101";
export const leftArrowText = "Navigate Before Icon";
export const policyDetailsHead = "Policy Details";
export const vehicleName = "Elena Rodriguez";
export const numberOfVEchiles = "2";
export const billingHead = "Billing Details";
export const price = "821.00";
export const dueDate = "01 Mar’24";
export const premiumHead = "Premium & Term Details";
export const annaulPrice = "2917.00";
export const term = "1 Year";
export const vaild = "02 Mar ‘23 - 01 Mar’24";
export const status = "Active";
export const dueOn = "Due on";
export const vehicles = "vehicles";
export const fileClaim = "File a claim";
export const MYCLAIM_ICON = myClaimsIcon;
export const CAR_ICON = carIcon;
export const STAR_ICON = starIcon;
export const PAYMENT_ICON = paymentHistoryIcon;
export const ASSISTANCE_ICON = roadsideAssistanceIcon;
export const LEARN_ICON = learnAboutIcon;
export const VIEW_ARROW = viewAllArrow;
export const LEFT_ARROW = leftArrow;
export const vehicle = "Vehicle";
export const driver = "Driver";
export const fileAClaim = "File a Claim";
export const clickToUpload = "Click to upload";
export const claimSubmitted = "Claim Submitted";
export const referenceNumber = "Please find you claim reference number ";
export const contactAgent="Contact your Agent for further process"
