export const StateName = [
    {country: "Buckinghamshire", value: "OK", label: "OK"},
  { country: "IND", value: "KA", label: "Karnataka" },
  { country: "IND", value: "TS", label: "Telangana" },
  { country: "IND", value: "AP", label: "Andra Predesh" },
  { country: "IND", value: "TN", label: "Tamil Nadu" },
  { country: "USA", value: "NY", label: "New York" },
  { country: "USA", value: "CA", label: "California" },
  { country: "USA", value: "TX", label: "Texas" },
  { country: "USA", value: "FL", label: "Florida" },
  { country: "AUS", value: "NSW", label: "New South Wales" },
  { country: "AUS", value: "VIC", label: "Victoria" },
  { country: "AUS", value: "QLD", label: "Queensland" },
  { country: "AUS", value: "WA", label: "Western Australia" },
  { country: "CAN", value: "ON", label: "Ontario" },
  { country: "CAN", value: "QC", label: "Quebec" },
  { country: "CAN", value: "BC", label: "British Columbia" },
  { country: "CAN", value: "AB", label: "Alberta" },
  { country: "MLI", value: "BK", label: "Bamako" },
  { country: "MLI", value: "GA", label: "Gao" },
  { country: "MLI", value: "KA", label: "Kayes" },
  { country: "MLI", value: "SK", label: "Sikasso" },
];
