const ProfileDetailsStyles = {
  profileDetailsContainer: {
    display: "flex",
    marginTop: "20px",
    "@media(max-width:1024px)": {
      display: "block",
    },
  },
  container: {
    maxWidth: "320px",
    height: "518px",
    borderRadius: "13px",
    background: "rgba(255, 255, 255, 1)",
    border: "1px solid rgba(201, 225, 236, 1)",
    padding: "0px 20px ",
    marginLeft: "30px",

    "@media(max-width:599px)": {
      margin: "0px auto",
    },
    "@media (min-width: 600px) and (max-width: 1024px)": {
      margin: "0px auto",
    },
  },
  profileDetailsHeading: {
    width: "127px",
    height: "22px",
    marginTop: "30px",
    marginLeft: "30px",
    gap: "0px",
    opacity: "0px",
    fontSize: "20px",
    fontWeight: "400",
    lineHeight: "22px",
    textAlign: "left",
  },
  labelStyle: {
    width: "65px",
    height: "15px",
    fontSize: "14px",
    fontWeight: "400",
    lineHeight: "15.4px",
    textAlign: "left",
  },
  tableHead: {
    marginLeft: "49px",
    fontFamily: "Noto Sans",
    marginRight: "10px",
    fontSize: "14px",
    fontWeight: "400",
    lineHeight: "24px",
    letterSpacing: "0px",
    textAlign: "left",
    opacity: "70%",
    width: "auto",
  },
  tableCells: {
    padding: "2px",
    fontFamily: "Noto Sans",
    fontSize: "14px",
    fontWeight: "400",
    paddingLeft: "22px",
    lineHeight: "24px",
    letterSpacing: "0px",
    textAlign: "left",
  },
  checkBox: {
    marginLeft: "-97px",
  },
  profileContainer: {
    width: "100%",
    maxWidth: "130px",
    margin: "0px auto",
    paddingTop: "21px",
    display: "flex",
    gap: "10px",
    flexDirection: "column",
  },
  profileImage: {
    width: "100%",
    img: {
      maxWidth: "121.01px",
    },
  },
  information: {
    display: "flex",
    gap: "5px",
    alignItems: "center",
    paddingBottom: "30px",
  },
  profileTextStyle: {
    fontFamily: "Noto Sans",
    fontSize: "14px",
    fontWeight: "400",
    lineHeight: " 20px",
    letterSpacing: "0em",
    textAlign: "left",
  },
  detailsContainer: {
    borderTop: "1px solid rgba(208, 209, 217, 1)",
    paddingTop: "30px",
    display: "flex",
    flexDirection: "column",
    gap: "25px",
  },
  detailsInfo: {
    display: "flex",
    gap: "10px",
  },
  settingsAndPreferences: {
    padding: "15px 30px 0px",
    // border: "2px solid",
    width: "100%",
    height: "auto",
    marginBottom: "500px",
    "@media(max-width:1023px)": {
      width: "85%",
      margin: "0px auto",
    },
  },
  settingsHeading: {
    fontFamily: "Playfair Display",
    fontSize: "18px",
    fontWeight: "400",
    lineHeight: "20px",
    letterSpacing: "0em",
    textAlign: "left",
    paddingBottom: "15px",
    borderBottom: " 1px solid rgba(208, 209, 217, 1)",
  },
  languagesHeading: {
    paddingTop: "20px",
    paddingBottom: "10px",
    fontFamily: "Noto Sans",
    fontSize: "16px",
    fontWeight: "400",
    lineHeight: "18px",
    letterSpacing: "0em",
    textAlign: "left",
  },
  textStyle: {
    paddingBottom: "25px",
    fontFamily: "Noto Sans",
    fontSize: "14px",
    fontWeight: "300",
    lineHeight: "15.4px",
    letterSpacing: "0em",
    textAlign: "left",
  },
};
export default ProfileDetailsStyles;
