const commonStyles = {
  fontFamily: "Noto Sans",
  fontSize: "18px",
  fontWeight: "300",
  lineHeight: "20px",
  letterSpacing: "0em",
  textAlign: "left",
};

const font = {
  fontFamily: "Noto Sans",
};

const PolicyStyles = {
  card: {
    display: "flex",
    gap: "0px",
  },
  policyCardHeading: {
    ...font,
    width: "100%",
    maxWidth: "257px",
    height: "22px",
    marginTop: "35.78px",
    marginLeft: "30px",
    marginRight: "auto",
    fontFamily: "Playfair Display",
    fontSize: "20px",
    fontWeight: "400",
    lineHeight: "22px",
    letterSpacing: "0em",
    textAlign: "left",
    color: "rgba(56, 61, 78, 1)",
    "@media (min-width:360px) and (max-width:599px)": {
      marginLeft: "25px",
      marginBottom: "10px",
      maxWidth: "150px",
    },
    "@media (min-width:600px) and (max-width:1024px)": {
      marginLeft: "32px",
    },
  },
  AllCards: {
    display: "flex",
    width: "100%",
    "@media (min-width:360px) and (max-width:767px)": {
      flexDirection: "column",
      width: "100%",
    },
    "@media (min-width: 768px) and (max-width: 1024px)": {
      width: "100%",
    },
  },
  oneCard: {
    width: "100%",
    maxWidth: "46.6921%",
    height: "367.47px",
    marginLeft: "30px",
    marginTop: "5.75px",
    borderRadius: "10px",
    boxShadow: "20px 20px 57px 0px rgba(0, 0, 0, 0.08)",

    "@media (min-width:360px) and (max-width:767px)": {
      width: "100%",
      maxWidth: "88.889%",
      marginLeft: "20px",
      marginTop: "15.95px",
      height: "584.42px",
    },
    "@media (min-width: 768px) and (max-width: 1024px)": {
      width: "100%",
      maxWidth: "44.4%",
      height: "540.42px",
    },
  },
  cardIcon: {
    width: "100%",
    maxWidth: "61.74px",
    height: "52.81px",
    marginTop: "40.03px",
    marginLeft: "40.02px",

    "@media (min-width:360px) and (max-width:599px)": {
      marginLeft: "30px",
      marginTop: "45.61px",
    },
    "@media (min-width:600px) and (max-width:1024px)": {
      marginLeft: "30px",
      marginTop: "45.61px",
    },
  },
  cardTopLeft: {
    display: "flex",
    gap: "128.5px",
    "@media (min-width:360px) and (max-width:599px)": {
      display: "block",
      gap: "20px",
    },
    "@media (min-width:600px) and (max-width:1024px)": {
      display: "block",
      gap: "40px",
    },
    "@media (min-width: 1025px) and (max-width: 1366px)": {
      display: "flex",
      gap: "80px",
    },
  },
  cardTopPolicyHeading: {
    ...font,
    width: "100%",
    maxWidth: "auto",
    height: "20px",
    marginTop: "50.61px",
    marginLeft: "18.22px",
    color: "rgba(29, 37, 43, 1)",
    fontSize: "18px",
    fontWeight: "300",
    lineHeight: "19.8px",
    letterSpacing: "0em",
    textAlign: "left",
    "@media (min-width:360px) and (max-width:599px)": {
      marginLeft: "28.26px",
      marginTop: "45.61px",
    },
    "@media (min-width:600px) and (max-width:1024px)": {
      marginLeft: "20.26px",
      marginTop: "45.61px",
    },
  },
  cardTopPolicyNumber: {
    ...font,
    width: "100%",
    maxWidth: "149px",
    height: "22px",
    marginTop: "3.89px",
    marginLeft: "18.22px",
    color: "rgba(29, 37, 43, 1)",
    fontSize: "20px",
    fontWeight: "400",
    lineHeight: "22px",
    letterSpacing: "0em",
    textAlign: "left",
    "@media (min-width:360px) and (max-width:599px)": {
      marginLeft: "28.26px",
    },
  },
  cardTopStatusHeading: {
    ...font,
    width: "100%",
    maxWidth: "51px",
    height: "20px",
    marginTop: "53.69px",
    color: "rgba(29, 37, 43, 1)",
    fontSize: "18px",
    fontWeight: "300",
    lineHeight: "19.8px",
    letterSpacing: "0em",
    textAlign: "left",
    marginRight: "40px",
    "@media (min-width:360px) and (max-width:599px)": {
      marginLeft: "-57px",
      marginTop: "30.19px",
      height: "19.6px",
      width: "auto",
    },
    "@media (min-width:600px) and (max-width:1024px)": {
      marginLeft: "-57px",
      marginTop: "40.19px",
      height: "19.6px",
      width: "auto",
    },
  },
  cardTopStatusDate: {
    ...font,
    width: "100%",
    maxWidth: "auto",
    height: "22px",
    marginTop: "2.89px",
    color: "rgba(29, 37, 43, 1)",
    fontSize: "20px",
    fontWeight: "400",
    lineHeight: "22px",
    letterSpacing: "0em",
    textAlign: "left",
    marginRight: "40px",
    "@media (min-width:360px) and (max-width:599px)": {
      marginLeft: "-57px",
      width: "auto",
      heigth: "21.56px",
    },
    "@media (min-width:600px) and (max-width:1024px)": {
      marginLeft: "-57px",
      width: "auto",
      heigth: "21.56px",
    },
  },
  cardBodyHeading: {
    ...font,
    width: "100%",
    maxWidth: "448px",
    height: "22px",
    marginTop: "50.5px",
    marginLeft: "40px",
    color: "rgba(29, 37, 43, 1)",
    fontSize: "20px",
    fontWeight: "400",
    lineHeight: "17px",
    letterSpacing: "0em",
    textAlign: "left",
    "@media (min-width:360px) and (max-width:599px)": {
      marginLeft: "30px",
      marginTop: "107px",
      width: "250px",
      height: "52px",
      lineHeight: "26px",
    },
    "@media (min-width: 600px) and (max-width: 1024px)": {
      marginLeft: "40px",
      marginTop: "90px",
      width: "350px",
      height: "auto",
      lineHeight: "26px",
      overFlow: "hidden",
      textOverflow: "ellipsis",
    },
    "@media (min-width: 1025px) and (max-width: 1366px)": {
      maxWidth: "290px",
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
  },

  autoDeduct: {
    display: "flex",
    "@media (min-width:360px) and (max-width:599px)": {
      display: "block",
    },
    "@media (min-width:600px) and (max-width:1024px)": {
      display: "block",
    },
  },
  cardBodyPremium: {
    ...font,
    ...commonStyles,
    width: "100%",
    maxWidth: "255px",
    height: "20px",
    marginTop: "15px",
    marginLeft: "40px",
    color: "rgba(29, 37, 43, 1)",

    "@media (min-width:360px) and (max-width:599px)": {
      marginLeft: "30px",
      marginTop: "15px",
      maxWidth: "282px",
      heigth: "20px",
      lineHeight: "19.8px",
    },
    "@media (min-width:600px) and (max-width:1024px)": {
      marginLeft: "40px",
      marginTop: "10px",
      width: "100%",
      maxWidth: "auto",
    },
  },
  cardBodyPremiumAuto: {
    ...font,
    ...commonStyles,
    width: "100%",
    maxWidth: "110px",
    marginTop: "13px",
    marginLeft: "5px",
    fontSize: "20px",
    fontWeight: "300",
    lineHeight: "19.8px",
    textAlign: "left",
    color: "rgba(13, 171, 34, 1)",
    "@media (min-width:360px) and (max-width:599px)": {
      maxWidth: "99px",
      height: "20px",
      marginLeft: "30px",
      marginTop: "12px",
      lineHeight: "19.8px",
    },
    "@media (min-width:600px) and (max-width:1024px)": {
      marginLeft: "40px",
      marginTop: "12px",
      maxWidth: "252px",
      heigth: "20px",
      lineHeight: "19.8px",
    },
  },
  cardBodyDueDate: {
    ...font,
    ...commonStyles,
    width: "100%",
    maxWidth: "200px",
    height: "20px",
    marginTop: "11px",
    marginLeft: "40px",
    "@media (min-width:360px) and (max-width:599px)": {
      marginLeft: "30px",
      marginTop: "12px",
      width: "230px",
      heigth: "52px",
      lineHeight: "26px",
    },
    "@media (min-width:600px) and (max-width:1024px)": {
      marginLeft: "40px",
      marginTop: "10px",
      width: "230px",
      heigth: "52px",
      lineHeight: "26px",
    },
  },
  cardBodyDay: {
    ...font,
    ...commonStyles,
    width: "100%",
    maxWidth: "72px",
    height: "20px",
    marginTop: "11px",
    color: "rgba(217, 77, 46, 1)",
    "@media (min-width:360px) and (max-width:599px)": {
      marginTop: "15px",
      maxWidth: "72px",
      heigth: "52px",
      lineHeight: "19.8px",
    },
    "@media (min-width:600px) and (max-width:1024px)": {
      marginTop: "14.3px",
    },
  },
  cardBodyInsure: {
    ...font,
    ...commonStyles,
    width: "100%",
    maxWidth: "auto",
    height: "20px",
    marginTop: "15px",
    marginLeft: "45px",
    "@media (min-width:360px) and (max-width:599px)": {
      marginLeft: "30px",
      marginTop: "15px",
      width: "250px",
      heigth: "20px",
      lineHeight: "19.8px",
    },
  },
  button: {
    width: "100%",
    maxwidth: "638px",
    display: "flex",
    justifyContent: "space-between",
    "@media (min-width:360px) and (max-width:599px)": {
      gap: "60px",
    },
  },
  policyCardViewAll: {
    fontFamily: "Noto Sans",
    fontSize: "18px",
    fontWeight: "400",
    lineHeight: "19.8px",
    textAlign: "left",
    cursor: "pointer",
    marginLeft: "0px",
    "@media (min-width:360px) and (max-width:599px)": {
      fontSize: "14px",
      maxWidth: "290px",
      marginTop: "3px",
    },
  },
  policyCardViewAllBox: {
    display: "flex",
    gap: "5px",
    marginTop: "25.78px",
    width: "90px",
    height: "15px",
    padding: "16px 30px 16px 12px",
    borderRadius: "30px",
    justifyContent: "flex-end",
    opacity: "0px",
    "@media (min-width:360px) and (max-width:599px)": {
      marginRight: "0px",
      marginTop: "35.78px",
    },
  },
  policyCardHead: {
    display: "flex",
    justifyContent: "space-between",
  },
  cardBottomButton: {
    fontFamily: "Lato",
    fontWeight: "400",
    width: "100%",
    maxWidth: "155px",
    height: "40px",
    marginTop: "27.54px",
    marginLeft: "39.03px",
    padding: "16px 12px",
    borderRadius: "40px",
    backgroundColor: "rgba(63, 63, 63, 1)",
    boxShadow: "0px 6px 10px 0px rgba(63, 63, 63, 0.3)",
    textTransform: "none",
    fontSize: "16px",
    lineHeight:"24px",
    "@media (min-width:360px) and (max-width:599px)": {
      marginLeft: "30px",
      marginTop: "45.54px",
      width: "155px",
      heigth: "40px",
      lineHeight: "19.8px",
    },
    "@media (min-width:600px) and (max-width:1024px)": {
      marginLeft: "40px",
      marginTop: "45.54px",
      width: "155px",
      heigth: "40px",
      lineHeight: "19.8px",
    },
  },

  ellipsisButton: {
    height: "25.7px",
    marginTop: "5px ",
    marginRight: "20px",
    "@media (min-width:360px) and (max-width:599px)": {
      marginTop: "28px ",
      img: {
        marginTop: "0px",
        width: "40px",
        height: "40px",
        lineHeight: "19.8px",
      },
    },
    "@media (min-width:600px) and (max-width:1024px)": {
      img: {
        marginTop: "50px",
        width: "40px",
        height: "40px",
        lineHeight: "19.8px",
      },
    },
  },
  rightArrow: {
    img: {
      width: "10.5px",
      marginBottom: "3px",
      "@media (min-width:360px) and (max-width:599px)": {
        width: "10.5px",
        marginTop: "10px",
      },
    },
  },
  oneCardTopSection: {
    cursor: "pointer",
  },
};

export default PolicyStyles;
