const CoverageTabStyles = {
  container: {
    marginTop: "20.5px",
    marginLeft: "0px",
    // padding:"0px"
    "@media(min-width:1367px)": {
      margin: "0px auto 0px auto",
    },
  },
  coverageAndLinks: {
    marginTop: "44px",
  },
  discounts: {
    marginTop: "49px",
  },
  coverageAndLinksHeading: {
    display: "flex",
    gap: "10px",
    alignItems: "center",
    marginBottom: "13px",
  },
  coverageAndLinksHeadingText: {
    fontFamily: "Playfair Display",
    fontSize: "20px",
    fontHeight: "400",
    lineHeight: "22px",
    letterSpacing: "0em",
    textAlign: "left",
  },
  discountsHeading: {
    display: "flex",
    gap: "10px",
    alignItems: "center",
    marginBottom: "13px",
  },
  discountsHeadingText: {
    fontFamily: "Playfair Display",
    fontSize: "20px",
    fontHeight: "400",
    lineHeight: "22px",
    letterSpacing: "0em",
    textAlign: "left",
  },
  responsiveContainer: {
    border: "1px solid #C9E1EC",
    padding: "0px 10px",
    borderRadius: "10px",
  },
  coveragesHead: {
    display: "flex",
    justifyContent: "space-between",
  },
  coveragesCard: {
    borderBottom: "1px solid #D0D1D9",
    padding: "15px 10px 20px 10px",
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  headText: {
    fontFamily: "Playfair Display",
    fontSize: "16px",
    fontWeight: "400",
    lineHeight: "17.6px",
    textAlign: "left",
    border: "1px solid #3F3F3F",
  },
  coveragesTextHeading: {
    fontFamily: "Noto Sans",
    fontSize: "14px",
    fontWeight: "400",
    lineHeight: "24px",
    textAlign: "left",
  },
  perItemText: {
    fontFamily: "Noto Sans",
    fontSize: "14px",
    fontWeight: "400",
    lineHeight: "24px",
    textAlign: "left",
    color: "#969696",
  },
  limitsText: {
    fontFamily: " Noto Sans",
    fontSize: "14px",
    fontWeight: "300",
    lineHeight: "15.4px",
    textAlign: "left",
  },
  limitsCount: {
    fontFamily: "Noto Sans",
    fontSize: "14px",
    fontWeight: "400",
    lineHeight: "19.07px",
    textAlign: "left",
  },
  coverages: {
    border: "1px solid #C9E1EC",
    padding: "0px 10px",
    borderRadius: "2px solid",
  },
  cardpremiums: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    padding: "15px 10px 19px 20px",
    borderBottom: "1px solid #C9E1EC",
  },
  limits: {
    display: "flex",
    gap: "10px",
    aliginItems: "center",
  },
  cardTotalPremiums: {
    padding: "15px 0px 20px 20px",
    display: "flex",
    flexDirection: "column",
    gap: "24px",
  },
  vechilePremiumValues: {
    display: "flex",
    gap: "85px",
  },
  tableHead: {
    fontFamily: "Nunito Sans",
    fontSize: "14px",
    fontWeight: "400",
    lineHeight: "24px",
    letterSpacing: "0px",
    textAlign: "left",
    opacity: "70%",
  },
  premiumFirstRow: {
    maxWidth: "40px",
  },
  premiumFirstTitle: {
    // paddingTop: "8px",
    // paddingLeft: "-5px",
    fontFamily: "Playfair Display",
    fontSize: "20px",
    fontWeight: "400",
    lineHeight: "22px",
    letterSpacing: "0em",
    textAlign: "left",
  },
  premiumTableCells: {
    display: "flex",
  },
  //   tableBodyCell: {

  //   },
  premiumTableRowCells: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  premiumTableCellValue: {
    fontFamily: "Noto Sans",
    fontSize: "20px",
    fontWeight: "400",
    lineHeight: "22px",
    letterSpacing: "0em",
    textAlign: "left",
  },
  premiumTableCellVechile: {
    fontFamily: "Noto Sans",
    fontSize: "18px",
    fontWeight: "300",
    lineHeight: "19.8px",
    letterSpacing: "0em",
    textAlign: "left",
  },
  tableBodyCell: {
    fontFamily: "Noto Sans",
    fontSize: "14px",
    fontWeight: "400",
    lineHeight: "24px",
    opacity: "100%",
    letterSpacing: "0px",
    textAlign: "left",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    maxWidth: "223px",
  },
};
export default CoverageTabStyles;
